### ISSUE TITLE
Not an issue, just a drive-by comment

### ISSUE THREAD

**Issue by romkatv** [lildude/dotfiles#1]
Hey there,

I randomly stumbled upon https://lildude.co.uk/speeding-up-my-zsh-shell and thought it worth mentioning that https://github.com/romkatv/zsh-bench exists. If you care about zsh performance, this project will likely prove useful.

I took a quick look at zshenv and zshrc and noticed this:

https://github.com/lildude/dotfiles/blob/cde5ad00e3cfcb1a2fc29744f2a0236a987303b2/chezmoi/private_dot_zshenv#L44

You need to move that line to the top of zshrc next to all other zstyles. Otherwise zsh will be a bit slower, rc files a bit more complex, and [ssh teleportation](https://github.com/romkatv/zsh4humans#ssh) won't work.

Cheers!

**Comment by romkatv** [comment]
Protip: Add `newline` before `prompt_char`: https://github.com/lildude/dotfiles/blob/cde5ad00e3cfcb1a2fc29744f2a0236a987303b2/chezmoi/dot_config/zsh/dot_p10k.zsh#L36

This will give you more space for typing commands and all commands -- current and past -- will start from the same position. Given that you are using transient prompt, it's a no-brainer to use a two-line prompt.

**Comment by lildude** [comment]
👋 @romkatv thanks for dropping by and commenting.

> ... thought it worth mentioning that https://github.com/romkatv/zsh-bench exists. If you care about zsh performance, this project will likely prove useful.

Oh yes. I've seen zsh-bench but hit the tmux issue you mention in the README the last time I tried to use it so haven't looked at it since. I'll def take a look at it again.

Thanks for the tip on moving the `chsh` option. I can't remember why I put it in `.zshenv` initially... probably to ensure it's run really early 😁 I don't use SSH teleportation (I rarely SSH into remote hosts these days) so wouldn't notice any breakage 🙈.

> Protip: Add `newline` before `prompt_char`:

Thanks. I'm still experimenting with all the different layouts and options p10k offers and will be experimenting with a two-line prompt soon.

**Comment by romkatv** [comment]
> I've seen zsh-bench but hit the tmux issue you mention in the README

I see this in your zshrc: https://github.com/lildude/dotfiles/blob/526d46de9c0ee30ff08aa80bd94b18d80d4c2942/chezmoi/dot_config/zsh/private_dot_zshrc#L27

Is this not up to date?

By the way, I highly recommend removing that line. It makes the UX worse as prompt keeps being jerked up and doesn't stay in a fixed position. Without that line prompt will always stay at the bottom, so you'll never have to search for it or to adjust your head/neck.

**Comment by lildude** [comment]
😆 I was just tinkering with that option yesterday and couldn't work out what difference it made other than downloading tmux onto each Codespace env I started. I tend to use quite a small terminal window (at the bottom of VSCode) so my prompt is always at the bottom.

**Comment by romkatv** [comment]
Got it. You can observe the difference if you trigger completions, press <kbd>Alt+R</kbd> (that's directory history), press <kbd>Ctrl+L</kbd> (clear screen), and a few other things. Integrated tmux is a fairly small binary compared to all the other things that zsh4humans installs. Everything is downloaded and installed in parallel, so there shouldn't be much of a difference w.r.t. installation time. That said, if it makes no difference in UX to you, it's totally fine to set `start-tmux` to `no`.

Closing as "resolved".

P.S.

I enjoyed the blog post, and not just because you ended up switching to zsh4humans 😅

**Comment by lildude** [comment]
> You can observe the difference if you trigger completions, press `Alt+R` (that's directory history), press `Ctrl+L` (clear screen)

Aaaah, I see now. Thanks.

> I enjoyed the blog post, and not just because you ended up switching to zsh4humans 😅

😍 Thanks.
